function handle(request, urlData) {
    if (urlData.parts.length !== 2) {
        ams.web.error.respondWithMessage("Unknown drop location: '{1}'.", [urlData.path], 404);
    }

    var sLocation = urlData.parts[1];
    if (sLocation === "all") {
        all()
    } else if (sLocation === "web") {
        web()
    }
}

function all() {
    ams.init();
    ams.log.debug("DROP AMS");
}

function web() {
    ams.loadWeb();
    ams.log.debug("DROP AMS/WEB");
}