function handleRequest(request) {
    // var user = tools_web.user_init(request, {});
    // alert(EncodeJson(user))

    var codelib = OpenCodeLib("controllers/main_controller.bs");

    codelib.handleRequest(request);
}

function handleRedirect(request) {
    if (ams.web.redirects.HasProperty(request.UrlPath)) {
        request.AddRespHeader("Location", ams.web.redirects.GetProperty(request.UrlPath), true);
        request.SetRespStatus(301, "");
    }

    request.SetRespStatus(404, "")
}